### ISSUE TITLE
attribute enableGestureRotate 

### ISSUE THREAD

**Issue by ghost** [Becavalier/Zoomage.js#5]
if I set enableGestureRotate as false,there will no picture display,how could I fix this

**Comment by Becavalier** [comment]
@Eric-Ji-0218 Hi Eric, I will fix this ASAP. Thanks for your feedback.

**Comment by Becavalier** [comment]
@Eric-Ji-0218 Sorry for that I cannot reproducing this issue, can you please attach some screenshots about this problem?

**Comment by ghost** [comment]
thank you!

**Comment by Becavalier** [comment]
Fixed in new release.
