### ISSUE TITLE
Get Image after manipulation

### ISSUE THREAD

**Issue by ilyatau** [Becavalier/Zoomage.js#6]
Hi,
Thanks for you good work. 
I found what script make css manipulation on canvas element, not changes in canvas.
Question is, how can I get image after manipulation? Regularly ( in img- touch-canvas), after manipulation I run canvas.toDataURL() and received base64 of image.
With this script I receive always same image without changes.
May be with zoomage I need make different. Do you know how get image?
Thanks

**Comment by Becavalier** [comment]
Hi, thank you for your question, what do you mean by "get image"? Here what Zoomage does is only change the watching viewpoint of the current image from your side, we don't do any changes on image itself.

**Comment by ilyatau** [comment]
Hi,
I want to change image and get base64 of new edited image.

**Comment by Becavalier** [comment]
Closed due to not going to provide this functionality.
